name: Create pull request to update prototype
on: 
  repository_dispatch:
    types: [release-created]
jobs:
  create-updating-pullrequest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make difference
      run: uuidgen > uuid.txt
    - name: Create pull request
      uses: peter-evans/create-pull-request@v2.7.1
      with:
        commit-message: Update prototype to ${{ github.event.client_payload.released_ref }}
        title: Update prototype to ${{ github.event.client_payload.released_ref }}
        branch: bot/update-prototype-${{ github.event.client_payload.released_ref }}
        base : develop