name: Receive Repository Dispatch
on: 
  repository_dispatch:
    types: [release-created]
jobs:
  receive-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event.client_payload) }}
