name: Receive Repository Dispatch
on: 
  repository_dispatch:
    types: [release-created]
jobs:
  receive-dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.released_ref }}; echo ${{ github.event.client_payload.released_sha }}
